title: Random Thoughts
description: Warranty void.
baseurl: ""
url: "https://vcsjones.dev"
twitter_username: vcsjones
github_username:  vcsjones
permalink: /:title/

markdown: kramdown
paginate: 5
sass:
  sourcemap: never
plugins:
  - jekyll-paginate
exclude:
  - _server
  - README.md
  - .github
  - .gitignore
  - .devcontainer.json
  - .startup.sh
  - .vscode
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - Dockerfile
