version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.6

    commands:
      - apt-get update -y
      - apt-get install -y webp exiftool pngcrush gzip brotli
  build:
    commands:
      - gem install bundler
      - bundle install
      - bundle exec jekyll build
      - bundle exec rake

artifacts:
  files:
    - _site/**/*
    - appspec.yml
    - _server/*
    - _deploy/*
  name: site
